version: "3.8"

services:
  db:
    image: mariadb:10.8-jammy
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: EUWO321093721jsahejwabne132145!@
    volumes:
      - ./data-volume:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306:3306
    depends_on:
      - db

  web:
    build: ./app/
    ports:
      - 8000:5000
    volumes:
      - ./app/src:/code:ro
        
  redis:
    image: "redis:7.0-alpine"

volumes:
  data-volume: 

