FROM sphinxdoc/sphinx AS build

WORKDIR /
COPY . .

WORKDIR /docs
RUN pip install sphinx_rtd_theme && make html -B

WORKDIR /docs/_build/html
CMD ["python", "-m", "http.server", "8000"]

# FROM python:3.9-alpine
# 
# WORKDIR /docs
# COPY --from=build /docs/_build/html .
# 
# CMD ["python", "-m", "http.server", "8000"]

