version: "3.8"

services:
  db:
    image: mariadb:10.8-jammy
    volumes:
      - ./data-volume:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - fastgrad_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    ports:
      - ${PMA_EXTERNAL_PORT}:80
    environment:
      PMA_HOST: ${MYSQL_INTERNAL_HOST}
      PMA_PORT: ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    depends_on:
      - db
    networks:
      - fastgrad_network

  api:
    build: ./app/
    ports:
      - ${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}
    volumes:
      - ./app/fastgrad_api:/app/fastgrad_api:ro
      - ./app/docs:/app/docs:ro
      - ./app/html:/app/html:ro
    environment:
      # remove this in production mode
      FLASK_DEBUG: 1
      FLASK_ENV: development
    networks:
      - fastgrad_network
    depends_on:
      - db
      - supertokens
    restart: unless-stopped
    # to run in a development mode
    command: ["flask", "run", "--reload"]
    # to directly debug from cli
    #command: ["tail", "-f", "/dev/null"]
    environment:
      MYSQL_INTERNAL_HOST: ${MYSQL_INTERNAL_HOST}
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
      MYSQL_API_USER: ${MYSQL_API_USER}
      MYSQL_API_PASS: ${MYSQL_API_PASS}
      MYSQL_DB: ${MYSQL_DB}


  frontend:
    build: ./frontend/
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
    volumes:
      - ./frontend/pages:/app/pages:ro
      - ./frontend/styles:/app/styles:ro
      - ./frontend/public:/app/public:ro
    # remove these lines for production
    command: pnpm run dev
    depends_on:
      - db
      - supertokens
    environment:
      NODE_ENV: development
    # -----
    networks:
      - fastgrad_network

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-mysql
    depends_on:
      - db
    ports:
      - ${SUPERTOKENS_EXTERNAL_PORT}:${SUPERTOKENS_INTERNAL_PORT}
    environment:
      MYSQL_CONNECTION_URI: "mysql://${MYSQL_SUPERTOKENS_USER}:${MYSQL_SUPERTOKENS_PASS}@${MYSQL_INTERNAL_HOST}:${MYSQL_INTERNAL_PORT}/${MYSQL_SUPERTOKENS_DB}"
      MYSQL_HOST: ${MYSQL_INTERNAL_HOST}
      MYSQL_PORT: ${MYSQL_INTERNAL_PORT}
      MYSQL_USER: ${MYSQL_SUPERTOKENS_USER}
      MYSQL_PASSWORD: ${MYSQL_SUPERTOKENS_PASS}
    networks:
      - fastgrad_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data-volume: 

networks:
  fastgrad_network:
    # driver: bridge
