version: "3.8"

services:
  db:
    image: mariadb:10.8-jammy
    ports:
      - 3306:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    volumes:
      - ./data-volume:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306:3306
    depends_on:
      - db
    networks:
      - app_network

  api:
    build: ./app/
    ports:
      - 8000:8000
    volumes:
      - ./app/fastgrad_api:/app/fastgrad_api:ro
      - ./app/docs:/app/docs:ro
      - ./app/html:/app/html:ro
    environment:
      # remove this in production mode
      FLASK_DEBUG: 1
      FLASK_ENV: development
    networks:
      - app_network
    depends_on:
      - db
      - supertokens
    restart: unless-stopped
    # to run in a development mode
    command: ["flask", "run", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    # to directly debug from cli
    #command: ["tail", "-f", "/dev#/null"]


  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend/pages:/app/pages:ro
      - ./frontend/styles:/app/styles:ro
      - ./frontend/public:/app/public:ro
    # remove these lines for production
    command: pnpm run dev
    depends_on:
      - db
      - supertokens
    environment:
      NODE_ENV: development
    # -----
    networks:
      - app_network

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-mysql
    depends_on:
      - db
    ports:
      - 3567:3567
    environment:
      MYSQL_CONNECTION_URI: "mysql://${MYSQL_SUPERTOKENS_USER}:${MYSQL_SUPERTOKENS_PASS}@${MYSQL_HOST}:${MYSQL_PORT}/$MYSQL_SUPERTOKENS_DB"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data-volume: 

networks:
  app_network:
    driver: bridge
